#!/bin/bash

# ============================================================================
# AWS Managed Blockchain - Deploy Vendored Chaincode (Fabric 2.2 Lifecycle)
# ============================================================================
# Based on AWS Official Documentation:
# https://docs.aws.amazon.com/managed-blockchain/latest/hyperledger-fabric-dev/managed-blockchain-hyperledger-develop-chaincode.html
#
# Key Points:
# 1. Fabric 2.2 uses NEW lifecycle (approve + commit, NOT instantiate)
# 2. Chaincode MUST have vendored dependencies (no internet in build env)
# 3. Use official Fabric samples as base (already vendored correctly)
# ============================================================================

set -e

# Network Configuration
export NETWORK_ID="n-CFCACD47IZA7DALLDSYZ32FUZY"
export MEMBER_ID="m-KTGJMTI7HFGTZKU7ECMPS4FQUU"
export PEER_NODE_ID="nd-ZQX2IJVXHBCWZOTRY5KXM2KDVA"
export ORDERER_URL="orderer.${NETWORK_ID}.managedblockchain.us-east-1.amazonaws.com:30001"
export PEER_ENDPOINT="${PEER_NODE_ID}.${MEMBER_ID}.${NETWORK_ID}.managedblockchain.us-east-1.amazonaws.com:30003"
export CHANNEL_NAME="mychannel"
export CC_NAME="supplychain"
export CC_VERSION="1.0"
export CC_SEQUENCE="1"

echo "============================================================================"
echo "STEP 1: Install Git and Go on EC2"
echo "============================================================================"
echo "Run these commands on EC2 instance:"
echo ""
echo "sudo yum update -y"
echo "sudo yum install -y git golang"
echo "go version"
echo "git --version"
echo ""
read -p "Press Enter after installing Git and Go on EC2..."

echo ""
echo "============================================================================"
echo "STEP 2: Clone Official Fabric Samples (v2.2.3)"
echo "============================================================================"
echo "Run on EC2:"
echo ""
echo "cd /home/ec2-user"
echo "git clone --branch v2.2.3 https://github.com/hyperledger/fabric-samples.git"
echo "cd fabric-samples/asset-transfer-basic/chaincode-go"
echo "ls -la"
echo ""
read -p "Press Enter after cloning fabric-samples..."

echo ""
echo "============================================================================"
echo "STEP 3: Vendor Go Dependencies on EC2"
echo "============================================================================"
echo "Run on EC2:"
echo ""
echo "cd /home/ec2-user/fabric-samples/asset-transfer-basic/chaincode-go"
echo "export GO111MODULE=on"
echo "go mod tidy"
echo "go mod vendor"
echo "ls -la vendor/"
echo ""
echo "This creates vendor/ folder with ALL Fabric dependencies included."
echo "The peer build container will NOT need internet access."
echo ""
read -p "Press Enter after vendoring dependencies..."

echo ""
echo "============================================================================"
echo "STEP 4: Check Docker CLI Container"
echo "============================================================================"
echo "Run on EC2:"
echo ""
echo "docker ps | grep cli"
echo ""
echo "If no 'cli' container is running, you need to start it."
echo "The cli container should mount /home/ec2-user to /opt/home"
echo ""
read -p "Press Enter if cli container is running..."

echo ""
echo "============================================================================"
echo "STEP 5: Package Chaincode with Vendored Dependencies (Fabric 2.2 Lifecycle)"
echo "============================================================================"
echo "Run on EC2 (inside cli container):"
echo ""
echo "docker exec -it cli bash"
echo ""
echo "# Inside the cli container:"
echo "cd /opt/home/fabric-samples/asset-transfer-basic/chaincode-go"
echo ""
echo "peer lifecycle chaincode package supplychain_1.0.tar.gz \\"
echo "  --path . \\"
echo "  --lang golang \\"
echo "  --label supplychain_1_0"
echo ""
echo "ls -la supplychain_1.0.tar.gz"
echo ""
echo "This package now includes the vendor/ folder!"
echo ""
read -p "Press Enter after packaging chaincode..."

echo ""
echo "============================================================================"
echo "STEP 6: (Optional) Remove Old Broken Install"
echo "============================================================================"
echo "Run inside cli container:"
echo ""
echo "peer lifecycle chaincode queryinstalled"
echo ""
echo "If you see old package ID (supplychain_1.0:b979b6a0d2ff...), remove it:"
echo ""
echo "peer lifecycle chaincode uninstall \\"
echo "  --package-id supplychain_1.0:b979b6a0d2fff9d8365964d7b105af58fc4d5700ad1bbb256e2c9798e4d0fea7"
echo ""
read -p "Press Enter after removing old package (or skip if not needed)..."

echo ""
echo "============================================================================"
echo "STEP 7: Install New Vendored Chaincode"
echo "============================================================================"
echo "Run inside cli container:"
echo ""
echo "cd /opt/home/fabric-samples/asset-transfer-basic/chaincode-go"
echo "peer lifecycle chaincode install supplychain_1.0.tar.gz"
echo ""
echo "peer lifecycle chaincode queryinstalled"
echo ""
echo "IMPORTANT: Copy the NEW Package ID from output!"
echo "Example: supplychain_1_0:abc123def456..."
echo ""
read -p "Enter the NEW Package ID: " NEW_PKG_ID
export CC_PACKAGE_ID="$NEW_PKG_ID"

echo ""
echo "============================================================================"
echo "STEP 8: Set Environment Variables in CLI Container"
echo "============================================================================"
echo "Run inside cli container:"
echo ""
echo "export ORDERER_URL=${ORDERER_URL}"
echo "export CHANNEL_NAME=${CHANNEL_NAME}"
echo "export CC_NAME=${CC_NAME}"
echo "export CC_VERSION=${CC_VERSION}"
echo "export CC_SEQUENCE=${CC_SEQUENCE}"
echo "export CC_PACKAGE_ID=${CC_PACKAGE_ID}"
echo ""
echo "# These should already be set by docker-compose, but verify:"
echo "export CORE_PEER_ADDRESS=${PEER_ENDPOINT}"
echo "export CORE_PEER_LOCALMSPID=${MEMBER_ID}"
echo "export CORE_PEER_MSPCONFIGPATH=/opt/home/fabric-certs-standard/admin-msp"
echo "export CORE_PEER_TLS_ROOTCERT_FILE=/opt/home/managedblockchain-tls-chain.pem"
echo ""
echo "# Verify:"
echo "env | grep CORE_PEER"
echo ""
read -p "Press Enter after setting environment variables..."

echo ""
echo "============================================================================"
echo "STEP 9: Approve Chaincode for Your Organization (Fabric 2.2 Lifecycle)"
echo "============================================================================"
echo "Run inside cli container:"
echo ""
echo "peer lifecycle chaincode approveformyorg \\"
echo "  -o \$ORDERER_URL \\"
echo "  --tls \\"
echo "  --cafile \$CORE_PEER_TLS_ROOTCERT_FILE \\"
echo "  --channelID \$CHANNEL_NAME \\"
echo "  --name \$CC_NAME \\"
echo "  --version \$CC_VERSION \\"
echo "  --package-id \$CC_PACKAGE_ID \\"
echo "  --sequence \$CC_SEQUENCE"
echo ""
echo "# Check readiness:"
echo "peer lifecycle chaincode checkcommitreadiness \\"
echo "  --channelID \$CHANNEL_NAME \\"
echo "  --name \$CC_NAME \\"
echo "  --version \$CC_VERSION \\"
echo "  --sequence \$CC_SEQUENCE \\"
echo "  --output json"
echo ""
echo "You should see: \"${MEMBER_ID}\": true"
echo ""
read -p "Press Enter after approving chaincode..."

echo ""
echo "============================================================================"
echo "STEP 10: Commit Chaincode Definition (Fabric 2.2 Lifecycle)"
echo "============================================================================"
echo "Run inside cli container:"
echo ""
echo "peer lifecycle chaincode commit \\"
echo "  -o \$ORDERER_URL \\"
echo "  --tls \\"
echo "  --cafile \$CORE_PEER_TLS_ROOTCERT_FILE \\"
echo "  --channelID \$CHANNEL_NAME \\"
echo "  --name \$CC_NAME \\"
echo "  --version \$CC_VERSION \\"
echo "  --sequence \$CC_SEQUENCE \\"
echo "  --peerAddresses \$CORE_PEER_ADDRESS \\"
echo "  --tlsRootCertFiles \$CORE_PEER_TLS_ROOTCERT_FILE"
echo ""
echo "# Verify commit:"
echo "peer lifecycle chaincode querycommitted \\"
echo "  --channelID \$CHANNEL_NAME \\"
echo "  --name \$CC_NAME"
echo ""
echo "If you see version 1.0 and sequence 1, chaincode is LIVE!"
echo ""
read -p "Press Enter after committing chaincode..."

echo ""
echo "============================================================================"
echo "STEP 11: Test Chaincode - Initialize Ledger"
echo "============================================================================"
echo "Run inside cli container:"
echo ""
echo "peer chaincode invoke \\"
echo "  -o \$ORDERER_URL \\"
echo "  --tls \\"
echo "  --cafile \$CORE_PEER_TLS_ROOTCERT_FILE \\"
echo "  -C \$CHANNEL_NAME \\"
echo "  -n \$CC_NAME \\"
echo "  -c '{\"Args\":[\"InitLedger\"]}'"
echo ""
echo "Wait 5-10 seconds for transaction to complete..."
echo ""
read -p "Press Enter after initializing ledger..."

echo ""
echo "============================================================================"
echo "STEP 12: Test Chaincode - Query All Assets"
echo "============================================================================"
echo "Run inside cli container:"
echo ""
echo "peer chaincode query \\"
echo "  -C \$CHANNEL_NAME \\"
echo "  -n \$CC_NAME \\"
echo "  -c '{\"Args\":[\"GetAllAssets\"]}'"
echo ""
echo "You should see JSON array of demo assets!"
echo ""
echo "🎉 If you see assets, YOUR BLOCKCHAIN IS FULLY FUNCTIONAL! 🎉"
echo ""
read -p "Press Enter after verifying query works..."

echo ""
echo "============================================================================"
echo "STEP 13: Test Create Asset"
echo "============================================================================"
echo "Run inside cli container:"
echo ""
echo "peer chaincode invoke \\"
echo "  -o \$ORDERER_URL \\"
echo "  --tls \\"
echo "  --cafile \$CORE_PEER_TLS_ROOTCERT_FILE \\"
echo "  -C \$CHANNEL_NAME \\"
echo "  -n \$CC_NAME \\"
echo "  -c '{\"Args\":[\"CreateAsset\",\"asset100\",\"blue\",\"5\",\"Tom\",\"1000\"]}'"
echo ""
echo "# Query the new asset:"
echo "peer chaincode query \\"
echo "  -C \$CHANNEL_NAME \\"
echo "  -n \$CC_NAME \\"
echo "  -c '{\"Args\":[\"ReadAsset\",\"asset100\"]}'"
echo ""
read -p "Press Enter after testing create asset..."

echo ""
echo "============================================================================"
echo "✅ CHAINCODE DEPLOYMENT COMPLETE!"
echo "============================================================================"
echo ""
echo "Next Steps:"
echo "1. Update Lambda environment variables with STANDARD network endpoints"
echo "2. Remove mock data fallback from Lambda code"
echo "3. Test Lambda → Blockchain connection"
echo "4. Test React UI → Lambda → Blockchain end-to-end"
echo "5. Record demo video"
echo "6. Clean up resources"
echo ""
echo "Network Endpoints for Lambda:"
echo "  ORDERER_URL: ${ORDERER_URL}"
echo "  PEER_ENDPOINT: ${PEER_ENDPOINT}"
echo "  CHANNEL_NAME: ${CHANNEL_NAME}"
echo "  CHAINCODE_NAME: ${CC_NAME}"
echo "  MSP_ID: ${MEMBER_ID}"
echo ""
echo "Cost: Network running at \$0.30/hour - complete testing within 24 hours!"
echo ""
echo "============================================================================"
